### ISSUE TITLE
Add Types

### ISSUE THREAD

**Issue by JNavas2** [Awesome-Windows/Awesome#311]
[Types](https://github.com/ystr/ystr.github.io/tree/master/types)
Types is a file type manager for Windows that allows you to edit program associations, icons, context menus and a few other things.

**Comment by rahulkapoor90** [comment]
Thanks for the recommendation, if you would like it to be added to the list, please create an Pull Request Instead. Thanks for Understanding!

**Comment by JNavas2** [comment]
Thanks for the suggestion, but:
- It's your list, not mine.
- I'm not currently setup to do GitHub Pull Requests, which is too much hassle just for this.
- Since you've not that interested in adding it, I'll just write it off as a waste of my time.

**Comment by rahulkapoor90** [comment]
https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request

**Comment by JNavas2** [comment]
As I said, it's too much hassle.

**Comment by rahulkapoor90** [comment]
No worries mate.

**Comment by JNavas2** [comment]
For a community project, use something more user friendly, like a Wiki.

**Comment by rahulkapoor90** [comment]
Thanks for the feedback! According to GitHub - Wikis provide a place in your repository to lay out the roadmap of your project, show the current status, and document software better, together. Maybe, you're talking about GitHub Gists? But, still the community still prefers and feels happy with the current procedure. 

Also, you don't need to copy-paste the same comment to all the issues created. Just something that might help you later on.

**Comment by JNavas2** [comment]
- GitHub is good (but not perfect) for _code_.
- For a simple list it's like carrying a computer to make phone calls.
- I repeated my comment just as you repeated the same useless advice.

_"If the only tool you have is a hammer, you will see every problem as a nail."_

**Comment by GaussSpace** [comment]
> * GitHub is good (but not perfect) for _code_.
> * For a simple list it's like carrying a computer to make phone calls.
> * I repeated my comment just as you repeated the same useless advice.
> 
> _"If the only tool you have is a hammer, you will see every problem as a nail."_

Sorry, I cannot agree with you.@JNavas2

* The collaboration method for pull requests may be more complicated, but it has its advantages.
* This is indeed a simple list in terms of content, but we should be accountable to the community.  Many people are suggested to look for the right software on this list, so caution is necessary.GitHub's repository management approach helps ensure the quality of this repository.
* Your statement is strange.  I think this project belongs to the community. If there are any problems in the community, we should start to improve. What you quote does not solve the problem.Since it is open source, can't you turn it into your favorite form?  If you blamed the problem here, why not try to fork it?
* Your opinion is interesting.  What is a user-friendly way of assisting?  Could it be that they simply fill out the form?  If so, it seems like a suggestion could be made.  Hollow rhetoric has no value, and actual problems can only be solved practically according to specific circumstances.  I think we can continue to discuss this issue.

**Comment by JNavas2** [comment]
@GaussSpace 
We'll just have to agree to disagree (on all those points).
_"If the only tool you have is a hammer, you will see every problem as a nail."_

**Comment by GaussSpace** [comment]
> @GaussSpace
> We'll just have to agree to disagree (on all those points).
> _"If the only tool you have is a hammer, you will see every problem as a nail."_

@JNavas2 
I think things should be seen in two parts ... extreme positions are not good for solving problems.
You think the opinion of the  maintainer is useless, but in fact your opinion is just as useless.  Your words seem to be just a defense of your actions. Why can't we decide this in a free way?At present,this behavior does not seem to be a manifestation of the spirit of the community.
> Entities should not be multiplied unnecessarily.

**Comment by JNavas2** [comment]
@GaussSpace 
Again, we'll just have to _agree to disagree_.
I'm not the one with the extreme position,
and I'm not the one engaging in _ad hominem_ attacks.
Have a nice day.
_"If the only tool you have is a hammer, you will see every problem as a nail."_

**Comment by GaussSpace** [comment]
@ JNavas2
I have no intention of offending you, and I apologize for my wrong words.
Let me try to clarify my point.  I think different people will have different opinions.  Some people may think that the pull request is too complicated, but others think just the opposite.  I think we should take care of as many people as possible. For example, a certain type of workflow can be packaged for easier use, while its original form is reserved for others to use (if they like).
So I don't think we can simply agree or disagree.
I apologize again for my wrong words.

**Comment by JNavas2** [comment]
@GaussSpace 
Apology accepted. I apologize for taking offense.

To be clear, I have no objection to other people using Git Pull requests if that's what they know and love. But Git is _massive overkill_ for a simple list, like using a semi-trailer truck to go to the local market for groceries. My objection is to having no reasonable alternative for those who aren't invested in Git. Otherwise your community is _very_ limited. If the list were just about code, that would be one thing, but a Windows list needs a Windows community.

I'm not interested in forking. I have my own blog, which is far more suited to my needs. But I'm happy to offer suggestions. And I did so, only to have those suggestions rejected out of hand because I didn't follow arcane, painful procedures. And before you defend them, let me assure you they are arcane and painful to those not invested in Git. It's like telling your mother to use vi.

There's an unfortunate tendency in the tech world to create solutions that only a techie can love, regular people be damned. It's why so much "good" tech goes nowhere in the real world. The genius of Apple was not in tech, which was actually invented by others. It was in making tech usable to regular people like your mother.

_"If the only tool you have is a hammer, you will see every problem as a nail."_

**Comment by GaussSpace** [comment]
@ JNavas2
Ok.  This statement makes sense.  But I still have reservations about it, because I think that technology like Git should be possible and better packaged so that ordinary people can simply use it, just as people communicate on the Internet today is much easier than it used to be.
I think the program should be as simple and easy to use as possible.  The technology community's neglect of ordinary users does have to work to completely change it, but every contribution they make is good for the community.I certainly hope that technology can be used by ordinary people.
Thank you for your detailed explanation of your comments in your reply.  Good luck.

**Comment by GaussSpace** [comment]
@JNavas2
Ok.  This statement makes sense.  But I still have reservations about it, because I think that technology like Git should be possible and better packaged so that ordinary people can simply use it, just as people communicate on the Internet today is much easier than it used to be.
I think the program should be as simple and easy to use as possible.  The technology community's neglect of ordinary users does have to work to completely change it, but every contribution they make is good for the community.I certainly hope that technology can be used by ordinary people.
Thank you for your detailed explanation of your comments in your reply.  good luck.
